{% set name = "fsl-pipe" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2ed02e1008ac5380c70737f7a6eba95667a45fdb8a77ae68b4f6537b7f09a81b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.6
    - file-tree
    - xarray
    - dask-core
    - fslpy
    - loguru
    - fsl-sub
    - python-graphviz

test:
  imports:
    - fsl_pipe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsl-pipe
  summary: Declarative pipelines based on Filetrees
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichielCottaar
