{% set name = "fsl-pipe" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ea6ffdca6db7ea3298e4e35058a001c1cb3e784a70ecbb24859c8bb82167ce6d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - file-tree
    - xarray
    - dask-core
    - fslpy
    - loguru
    - fsl-sub
    - python-graphviz

test:
  imports:
    - fsl_pipe
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsl-pipe
  summary: Declarative pipelines based on Filetrees
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichielCottaar
