{% set name = "fsl-pipe" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fsl-pipe-{{ version }}.tar.gz
  sha256: a1382e9a87c0304791dfb8d4e86ad8d538ddcd72d93f47838f02a13f5f4feef0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.6
    - file-tree
    - xarray
    - dask-core
    - fslpy
    - loguru
    - fsl-sub
    - python-graphviz

test:
  imports:
    - fsl_pipe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.fmrib.ox.ac.uk/ndcn0236/fsl-pipe
  summary: Declative pipelines based on Filetrees
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichielCottaar
