{% set name = "fsl-pipe" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fsl-pipe-{{ version }}.tar.gz
  sha256: 9979ea0cb35f33ca063d1e59de279e67d7bb27775e3109c19d2f16d6fcc416e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.6
    - file-tree
    - xarray
    - dask-core
    - fslpy
    - loguru
    - fsl-sub
    - python-graphviz

test:
  imports:
    - fsl_pipe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsl-pipe
  summary: Declarative pipelines based on Filetrees
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichielCottaar
